/**
 * Envelope + gas-analytics parsing tests.
 *
 * Fixtures are generated by scripts/generate-fixtures.js (synthetic but
 * structurally valid XDR built with the Stellar SDK).
 *
 * Run with: npm test
 */

import * as fs from 'fs';
import * as path from 'path';
import { SorobanParser } from '../src/parser';
import { TransactionTrace } from '../src/types';

const fixture = (name: string) =>
  JSON.parse(
    fs.readFileSync(path.join(__dirname, 'fixtures', name), 'utf-8')
  );

describe('SorobanParser - envelope decoding', () => {
  let trace: TransactionTrace;

  beforeAll(() => {
    trace = new SorobanParser().parseTransaction(fixture('invoke-transfer.json'));
  });

  it('decodes the invoked contract, function and arguments', () => {
    expect(trace.operations).toHaveLength(1);
    const op = trace.operations[0];
    expect(op.type).toBe('call');
    expect(op.contractId).toMatch(/^C[A-Z2-7]{55}$/);
    expect(op.functionName).toBe('transfer');
    expect(op.parameters).toHaveLength(3);
    expect(op.parameters[0]).toMatch(/^G[A-Z2-7]{55}$/);
    expect(op.parameters[2].toString()).toBe('2500000');
  });

  it('marks the operation successful and carries the meta return value', () => {
    expect(trace.success).toBe(true);
    expect(trace.operations[0].error).toBeUndefined();
    expect(trace.operations[0].returnValue).toBe(true);
  });

  it('extracts the transfer event from the meta XDR', () => {
    expect(trace.events).toHaveLength(1);
    const event = trace.events[0];
    expect(event.contractId).toMatch(/^C[A-Z2-7]{55}$/);
    expect(event.topics[0]).toBe('transfer');
    expect(event.data.toString()).toBe('2500000');
  });

  it('extracts declared Soroban resources from sorobanData', () => {
    expect(trace.gas).toBeDefined();
    expect(trace.gas!.cpuInstructions).toBe(3214876);
    expect(trace.gas!.diskReadBytes).toBe(4920);
    expect(trace.gas!.writeBytes).toBe(128);
    expect(trace.gas!.declaredResourceFeeStroops).toBe('1043216');
  });

  it('extracts the charged resource-fee breakdown from meta ext v1', () => {
    expect(trace.gas!.nonRefundableFeeStroops).toBe('890123');
    expect(trace.gas!.refundableFeeStroops).toBe('153093');
    expect(trace.gas!.rentFeeStroops).toBe('41210');
    expect(trace.gas!.totalResourceFeeStroops).toBe('1043216');
  });

  it('derives the inclusion fee from feeCharged minus resource fee', () => {
    // 1_100_000 charged - 1_043_216 resource = 56_784
    expect(trace.gas!.totalFeeChargedStroops).toBe('1100000');
    expect(trace.gas!.inclusionFeeStroops).toBe('56784');
  });
});

describe('SorobanParser - upload transaction', () => {
  it('flags an uploadContractWasm operation and stashes the bytes', () => {
    const trace = new SorobanParser().parseTransaction(fixture('upload-wasm.json'));
    expect(trace.operations[0].type).toBe('upload');
    expect(trace.operations[0].functionName).toBe('upload_wasm');
    expect(Buffer.isBuffer(trace._pendingWasm)).toBe(true);
  });
});
